#pragma once
// Documentation-build shim for Folly's generated folly-config.h.
#define FOLLY_HAVE_PTHREAD 1
#define FOLLY_HAVE_PTHREAD_ATFORK 1
#define FOLLY_HAVE_LIBGFLAGS 0
#define FOLLY_HAVE_LIBGLOG 0
#define FOLLY_HAVE_MALLOC_H 0
#define FOLLY_HAVE_MEMRCHR 0
#define FOLLY_HAVE_CLOCK_GETTIME 1
#define FOLLY_HAVE_INT128_T 1
#define FOLLY_HAVE_WCHAR_SUPPORT 1
#define FOLLY_HAVE_UNALIGNED_ACCESS 1
#define FOLLY_HAVE_WEAK_SYMBOLS 1
#define FOLLY_HAVE_ELF 0
#define FOLLY_HAVE_DWARF 0
#define FOLLY_HAVE_BACKTRACE 0
#define FOLLY_USE_JEMALLOC 0
#define FOLLY_USE_LIBCPP 1
#define FOLLY_MOBILE 0
#define FOLLY_HAVE_LIBRT 0
#define FOLLY_HAVE_LIBUNWIND 0
#define FOLLY_VERSION "0000.00.00.00"
